#!/usr/bin/env python3
"""Generate CATALOGUE.md: every database in the project, what it is, and what its licence requires.

  python3 -m megasamples catalogue [--container megasamples-mysql] [--check]

The README says what the project is; this says what is *in* it. One row per dataset, with the tier
that decides whether it is in the image, its measured shape, its licence, and whether that licence
asks anything of someone who redistributes it.

Sources, in order of authority: `megasamples.datasets` inside the running image for the measured
shape (the same table `tests/image_test.py` asserts against), `datasets/*/dataset.yaml` for the tier
and licence ids of everything else, and the knowledge records for the one-line description. Nothing
here is typed by hand, so it cannot drift from what was built. `--check` exits non-zero if the file
would change, which is what `make check` runs.
"""
import argparse, os, subprocess, sys

import yaml

from megasamples.paths import ROOT
OUT = os.path.join(ROOT, "CATALOGUE.md")
README = os.path.join(ROOT, "README.md")
README_START, README_END = "<!-- databases:start -->", "<!-- databases:end -->"
GENERATED = ("<!-- Generated by megasamples/catalogue.py from megasamples.datasets and datasets/*/dataset.yaml.\n"
             "     Do not edit by hand: `make catalogue` overwrites it. -->\n")
TIER_NOTE = {
    "core": "in the image",
    "core-medium": "in the image",
    "extended": "opt-in; `make <name>`",
    "generated": "generated on your machine",
    "user-fetched": "you download it; never redistributed",
    # citibike and divvy sit here because *this project* ships none of their data; the loaders are
    # shipped and you run them yourself, which is where their licences put the boundary
    "not-shipped": "loaders only; you fetch the data, it is never redistributed",
}


def query(container, sql):
    p = subprocess.run(["docker", "exec", container, "mysql", "-uroot", "-proot", "-N", "--batch",
                        "-e", sql], capture_output=True, text=True)
    return [l.split("\t") for l in p.stdout.splitlines() if l.strip()] if p.returncode == 0 else []


# Where the one-line "what is this" comes from, for both the catalogue and the console landing page.
# The dataset's own research record already says it, and reusing that means a description cannot
# drift from the research or be invented by whoever last edited a template.
# No ". " here: it cuts "11,140 rows incl. 8,640 multilingual products" at the abbreviation and
# leaves a sentence ending in "incl". The other separators plus the length ceiling are enough.
SPLITS = ("; ", " - ", " \u2014 ")


def record_description(path):
    """The dataset's description, cut back to the clause that says what it is.

    The records say what the dataset is and then how it is obtained -- "shipped as .bak files",
    "needs no SQL Server to read", "proposed for the core tier". A reader wants the first part; the
    rest is in PROVENANCE.md and in the table's own columns."""
    if not path or not os.path.exists(os.path.join(ROOT, path)):
        return ""
    text = open(os.path.join(ROOT, path), encoding="utf-8").read()
    try:
        meta = yaml.safe_load(text.split("---", 2)[1])
    except Exception:
        return ""
    return shorten((meta or {}).get("description", "").strip())


def shorten(full, floor=40, ceiling=150):
    head = full
    for sep in SPLITS:
        candidate = head.split(sep)[0].strip()
        if len(candidate) >= floor:
            head = candidate
    if len(head) > ceiling:                       # one long clause: end it at a comma, not mid-word
        cut = head.rfind(", ", 0, ceiling)
        if cut > floor:
            head = head[:cut]
    if head.count("(") > head.count(")"):         # never leave a parenthesis hanging open
        opened = head.rfind("(")
        if opened > floor:
            head = head[:opened]
    return head.rstrip(" .,;-")


# The curated tags on each licence record, mapped to what they mean for someone redistributing.
# Read from the record's frontmatter rather than inferred from its prose: scanning the text for
# "share-alike" labels MIT as copyleft, because the MIT record explains that it is *not* one.
TAG_MEANS = {
    "share-alike": "share-alike",
    "copyleft": "share-alike",
    "attribution": "attribution",
    "attribution-required": "attribution, verbatim disclaimer",
    "permissive": "ship the notice",
    "public-domain": "none",
    "redistribution-blocked": "**cannot be redistributed**",
    "proprietary": "**build-time only, never redistributed**",
    "eula": "**build-time only, never redistributed**",
}


def licence_obligations():
    """What each licence asks of a redistributor, from the curated tags on its record."""
    out = {}
    d = os.path.join(ROOT, "knowledge", "licenses")
    for f in sorted(os.listdir(d)):
        if not f.endswith(".md") or f == "index.md":
            continue
        text = open(os.path.join(d, f), encoding="utf-8").read()
        try:
            meta = yaml.safe_load(text.split("---", 2)[1]) or {}
        except Exception:
            meta = {}
        asks = [TAG_MEANS[t] for t in (meta.get("tags") or []) if t in TAG_MEANS]
        spread = [part for a in asks for part in a.split(", ")]
        out[f[:-3]] = ", ".join(dict.fromkeys(spread)) or "see the record"
    return out


def pinned_counts(dataset):
    """{table: rows} from tests/expected_counts.yaml: the counts every image is tested against, and
    what the registry inside an image carries. Read from the repository, so the catalogue is the
    same on a fresh clone as on a machine that has built the images."""
    path = os.path.join(ROOT, "datasets", dataset, "tests", "expected_counts.yaml")
    if not os.path.exists(path):
        return None
    counts = yaml.safe_load(open(path, encoding="utf-8")) or {}
    return {t: int(n) for t, n in counts.items() if isinstance(n, int)}


def collect(container=None):
    # The shape comes from the pinned expectations, not from a running image: `information_schema`
    # sizes move with every restart, and an image is not always on the machine. The core tier is
    # what the default image bakes; every image is tested against these same counts.
    from megasamples import datasets as inventory
    core_names = set(inventory.core())            # what the default image bakes: the `core` selector
    out = []
    for d in sorted(os.listdir(os.path.join(ROOT, "datasets"))):
        spec_path = os.path.join(ROOT, "datasets", d, "dataset.yaml")
        if not os.path.exists(spec_path):
            continue
        spec = yaml.safe_load(open(spec_path, encoding="utf-8")) or {}
        db = spec.get("database", d)
        append = bool(spec.get("append"))
        counts = pinned_counts(d) if d in core_names else None
        ports_path = os.path.join(ROOT, "datasets", d, "ports", "not_ported.yaml")
        ports = yaml.safe_load(open(ports_path, encoding="utf-8")) or {} if os.path.exists(ports_path) else {}
        out.append(dict(
            name=d,
            database=db,
            ports={e: len(v or []) for e, v in ports.items()},
            tier=spec.get("tier", "?"),
            licences=spec.get("licenses", []) or [],
            record=spec.get("record", ""),
            # `blurb:` in dataset.yaml wins where the record's description was written for the
            # research rather than for a reader -- smallsets' explains which naming option was
            # accepted, which means nothing to someone looking at a list of databases
            what=(spec.get("blurb") or record_description(spec.get("record", "")))
                 + (" — a live feed: a build takes the current extract, and this count is the snapshot's floor" if spec.get("live") else ""),
            append=append,
            tables=len(counts) if counts else None,
            rows=sum(counts.values()) if counts else None,
        ))
    return out


def render(items):
    asks = licence_obligations()
    in_image = [i for i in items if i["tables"] is not None]
    total_tables = sum(i["tables"] for i in in_image)
    total_rows = sum(i["rows"] or 0 for i in in_image)

    L = [GENERATED.rstrip(), "", "# Catalogue", "",
         f"**{len(in_image)} databases in the core image** — {total_tables:,} tables, {total_rows:,} rows — "
         "plus the datasets that are opt-in, generated on your machine, or that you fetch yourself.",
         "", "Generated from `datasets/*/dataset.yaml`, each core dataset's pinned `tests/expected_counts.yaml` (the",
         "counts every image is tested against) and each dataset's `ports/not_ported.yaml`, so it cannot drift",
         "from what is built. `README.md`",
         "explains the project; `datasets/<name>/PROVENANCE.md` has the full derivation of any one row.",
         "", "The **engines** column names the engines a dataset has been built and verified on. PostgreSQL and",
         "SQLite are ports of the MySQL corpus with the same rows, checked by the same content digests;",
         "\"not ported\" counts the views, routines, triggers and full-text or spatial indexes that engine does",
         "not carry, listed by name in `datasets/<name>/ports/not_ported.yaml`.", ""]

    for tier in ("core", "core-medium", "extended", "generated", "user-fetched", "not-shipped"):
        group = [i for i in items if i["tier"] == tier]
        if not group:
            continue
        L += [f"## {tier} — {TIER_NOTE.get(tier, '')}", "",
              "| database | what it is | tables | rows | engines | licence | asks of a redistributor |",
              "|---|---|---:|---:|---|---|---|"]
        for i in group:
            lic = ", ".join(f"[{x}](knowledge/licenses/{x}.md)" for x in i["licences"]) or "—"
            parts = [p for x in i["licences"] for p in asks.get(x, "").split(", ") if p]
            parts = list(dict.fromkeys(parts))
            if len(parts) > 1:                      # "none" alongside a real obligation is noise
                parts = [p for p in parts if p != "none"]
            ask = ", ".join(parts) or "—"
            t = f"{i['tables']:,}" if i["tables"] is not None else "—"
            r = f"{i['rows']:,}" if i["rows"] else "—"
            label = f"`{i['name']}`" + (f"<br>appends to `{i['database']}`" if i["append"] else "")
            what = i["what"].replace("|", "\\|")
            engines = ["MySQL"] if i["tables"] is not None else []
            for e, title in (("postgres", "PostgreSQL"), ("sqlite", "SQLite")):
                if e in i["ports"]:
                    engines.append(f"{title} ({i['ports'][e]} not ported)" if i["ports"][e] else title)
            L.append(f"| {label} | {what} | {t} | {r} | {' · '.join(engines) or '—'} | {lic} | {ask} |")
        L.append("")

    L += ["TPC-C is generated too, by `make load-tpcc`, but has no `datasets/*/dataset.yaml` and so no",
          "row above: it is loaded by `megasamples/sources/tpcc_load.py` through sysbench rather than by the",
          "fetch/stage/load pipeline, and it is the one dataset with no pinned content digests, because",
          "its generator does not produce the same rows twice (`knowledge/datasets/tpc-c.md`).",
          "",
          "## What the obligations mean", "",
          "* **attribution** — the notice in `datasets/<name>/LICENSE` and the root `NOTICE.md` has to",
          "  travel with the data, including inside a derived image.",
          "* **share-alike** — a modified or extended version of that database must be offered under",
          "  the same licence. This applies to `employees`, `lahman`, the Stack Exchange datasets and",
          "  `wikipedia_simple`.",
          "* **verbatim disclaimer** — Chicago's terms require their disclaimer word for word, and",
          "  reserve the City's right to require distribution to stop. It is in `README.md` and",
          "  `NOTICE.md`.",
          "",
          "Citi Bike and Divvy are in this catalogue because the project ships loaders for them. Their",
          "data is never redistributed here in any form: both licences prohibit hosting or distributing",
          "it as a stand-alone dataset.", ""]
    return "\n".join(L)


def readme_block(items):
    """The core-tier list the README carries, generated from the same source as the catalogue."""
    rows = ["| database | what it is | tables | rows |", "|---|---|---:|---:|"]
    for i in items:
        if i["tier"] not in ("core", "core-medium") or i["tables"] is None:
            continue
        what = i["what"].replace("|", "\\|")
        rows.append(f"| `{i['name']}` | {what} | {i['tables']:,} | {i['rows']:,} |")
    return "\n".join(rows)


def splice_readme(items, check):
    text = open(README, encoding="utf-8").read()
    if README_START not in text or README_END not in text:
        return ["README.md has no <!-- databases:start --> block"] if check else []
    head, rest = text.split(README_START, 1)
    _, tail = rest.split(README_END, 1)
    new = f"{head}{README_START}\n{readme_block(items)}\n{README_END}{tail}"
    if check:
        return [] if new == text else ["README.md's database list is out of date; run `make catalogue`"]
    if new != text:
        open(README, "w", encoding="utf-8").write(new)
    return []


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--container", default="megasamples-mysql")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args(argv)

    items = collect(a.container)
    text = render(items)
    if a.check:
        problems = splice_readme(items, check=True)
        current = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if current != text:
            problems.append("CATALOGUE.md is out of date; run `make catalogue`")
        for p_ in problems:
            print(f"  x {p_}")
        if problems:
            return 1
        print("  . CATALOGUE.md and the README list are up to date")
        return 0
    open(OUT, "w", encoding="utf-8").write(text)
    splice_readme(items, check=False)
    measured = sum(1 for i in items if i["tables"] is not None)
    print(f"  . wrote CATALOGUE.md: {len(items)} datasets, {measured} with pinned table and row counts")
    return 0


if __name__ == "__main__":
    sys.exit(main())
